version: '3.7'

services:
  app:
    image: node:12-alpine
    container_name: twinkle-be
    command: sh -c "
      npm install
      && npm i -g sequelize-cli
      && sequelize db:migrate
      && npm run dev"
    ports:
      - 3000:3000
      - 9229:9229
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:12.5
    container_name: twinkle-database
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root

volumes:
  db-data:
