version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run: npm run test:up
      - run: sleep 60 && npm test

workflows:
  version: 2
  just_test:
    jobs:
      - test



