version: 2.1

jobs:
  setup:
    docker:
      - image: circleci/node:12.14.1
      - image: node:12-alpine
      - image: postgres:12.5
        environment:
          POSTGRES_PASSWORD: root
    steps:
      - checkout
      - run:
          name: install sequelize-cli
          command: npm install -g sequelize-cli
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: migrate DB
          command: npx sequelize db:migrate
      - run:
          name: run instance
          command: npm run dev
  test:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - run: npm run test



workflows:
  version: 2
  just_test:
    jobs:
      - setup
      - test:
          requires:
            - setup



